print("Hola mundo")
print(554+1)
print('Hola me llamo "Milton" y tu?')
print("Hola" + " "+ 'fede')
print("Me llamo \"Milton\"")
print("Esta es una linea \nY esta es otra linea")
print("\tEsta es la tercera linea")
print('this isn\'t a number')
print("este signo \\ es una barra invertida")
